name: doctor_rounds
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  date_field: ^3.0.5
  flutter_typeahead: ^4.6.1
  collection: ^1.15.0
  simple_animations: ^5.0.1
  modal_progress_hud_nsn: ^0.4.0
  syncfusion_flutter_datagrid: ^21.2.8
  vertical_tabs_flutter: ^1.0.0
  webview_flutter: ^4.2.2
  deep_collection: ^1.0.2
  syncfusion_flutter_core: ^21.2.8
  autocomplete_textfield: ^2.0.1
  searchable_paginated_dropdown: ^1.2.0
  awesome_select: ^6.0.0
  vertical_scrollable_tabview: ^0.1.0
  flutter_spinkit: ^5.1.0
  back_button_interceptor: ^6.0.2
  flutter_page_view_indicator: ^0.0.5
  dots_indicator: ^3.0.0
  theme_patrol: ^2.2.1
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.1
  rive: ^0.11.2
  # flutter_widget_from_html: ^0.6.0

  flutter_switch: ^0.3.2
  syncfusion_flutter_calendar: ^21.2.8
  fab_circular_menu: ^1.0.1
  #  floating_search_bar: ^0.3.0
  auto_size_text: ^3.0.0
  http: ^0.13.3
  json_annotation: ^4.8.1
  shared_preferences: any
  fluttertoast: ^8.2.1
  # downloads_path_provider_28: ^0.1.2
  sqflite: ^2.2.8+4
  dropdown_search: ^5.0.6
  dropdown_search2:
    path: ./lib/custom_dropdown
  # flutter_audio_recorder2: ^0.0.2
  #  audio_recorder: ^1.0.2
  file: any
  material_floating_search_bar_2: ^0.5.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  table_sticky_headers: ^2.0.5
  buttons_tabbar: ^1.3.0
  syncfusion_flutter_charts: ^21.2.8
  connectivity_plus: ^4.0.1
  mac_address: ^1.0.0
  device_info: ^2.0.2
  file_picker: ^5.3.2
  wifi_info_plugin_plus: ^2.0.2

  flutter_progress_hud: ^2.0.2
  # wifi_info_plugin: ^1.1.5
  image_picker: ^0.8.0+1
  path_provider: ^2.0.15
  open_file: ^3.2.1
  permission_handler: ^10.3.0
  # webview_flutter: ^1.0.7
  toggle_switch: ^2.1.0
  provider: ^6.0.3
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.1.11
  # vertical_scrollable_tabview: ^0.0.7
  searchfield: ^0.8.3
  vertical_tab_bar_view: ^0.0.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  json_serializable: ^6.7.0

dependency_overrides:
  meta: "1.7.0"
  http: "0.13.3"
  ffi: "2.0.1"
  dbus: "0.7.5"
  xml: "6.1.0"
  flutter_svg: "0.22.0"
  flutter_math_fork: any
  provider: "5.0.0"
  collection: "1.15.0"
  async: "2.8.1"
#  analyzer: ^0.39.10
#  build_resolvers: '1.3.10'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/database/
    - assets/images/i-inpatientz.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #emulater nexus7
  #dart sdk 3.4.1
  #flutter sdk 3.22.1
